openapi: 3.0.0
info:
  title: Fake eCommerce Store API
  version: 1.0.0
  description: API for fetching products and categories from the Fake Store API via Express back-end.
servers:
  - url: http://localhost:3000
paths:
  /api/products:
    get:
      summary: Get all products
      responses:
        '200':
          description: List of all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /api/products/categories:
    get:
      summary: Get all product categories
      responses:
        '200':
          description: List of all categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/products/category/{category}:
    get:
      summary: Get products by category
      parameters:
        - in: path
          name: category
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of products in the category
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        price:
          type: number
        description:
          type: string
        category:
          type: string
        image:
          type: string
        rating:
          type: object
          properties:
            rate:
              type: number
            count:
              type: integer
